server:
  tomcat:
    apr-enabled: false
spring:
  application:
    name: quickstart
  datasource:
    url: jdbc:postgresql://localhost:5432/quickstart
    username: quickstart_user
    password: quickstart_pw
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 45000 # 45 seconds
      idle-timeout: 240000 # 4 minutes
      max-lifetime: 300000 # 5 minutes
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info